name: Codecov

on:
  pull_request:
    branches:
      - main

jobs:
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run tests and collect coverage
        run: pnpm jest:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hikoinc/hikoui-beta
