name: Quality

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run ESLint
        run: pnpm eslint

  typescheck:
    name: TypeScript
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Type Check
        run: pnpm typescheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: [eslint, typescheck]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Prettier Check
        run: pnpm prettier:check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [eslint, typescheck, prettier]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run
        run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [eslint, typescheck, prettier, tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Project Build
        run: pnpm build
