name: Quality Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-artifacts:
    name: Build Project Artifacts
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-artifact
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Project Build
        run: pnpm build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-artifact
          path: packages/**/dist

  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest
    needs:
      - build-artifacts
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: packages/

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run ESLint and Stylelint Checks
        run: pnpm lint

  check-types:
    name: Check TypeScript Types
    runs-on: ubuntu-latest
    needs:
      - lint-code
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: packages/

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Type Check
        run: pnpm typescheck

  check-formatting:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    needs:
      - lint-code
      - check-types
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Prettier Check
        run: pnpm prettier:check

  check-package-json:
    name: Check Package.json Sorting
    runs-on: ubuntu-latest
    needs:
      - lint-code
      - check-types
      - check-formatting
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Sort Package Json Check
        run: pnpm sort-package-json:check

  run-tests:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    needs:
      - lint-code
      - check-types
      - check-formatting
      - check-package-json
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: packages/

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run tests and collect coverage
        run: pnpm test
