name: Quality

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-artifact
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Project Build
        run: pnpm build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-artifact
          path: packages/**/dist

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: packages/

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run ESLint
        run: pnpm eslint

  typescheck:
    name: TypeScript
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: packages/

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Type Check
        run: pnpm typescheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: [eslint, typescheck]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Prettier Check
        run: pnpm prettier:check

  sort-package-json:
    name: Sort Package Json
    runs-on: ubuntu-latest
    needs: [eslint, typescheck, prettier]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run Sort Package Json Check
        run: pnpm sort-package-json:check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [eslint, typescheck, prettier, sort-package-json]
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: packages/

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Run tests and collect coverage
        run: pnpm jest:coverage
