name: Quality

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup
        with:
          node-version: "20"

      - name: Run ESLint
        run: pnpm eslint

  typescheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup
        with:
          node-version: "20"

      - name: Run TypeScript Check
        run: pnpm typescheck

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup
        with:
          node-version: "20"

      - name: Run Prettier Check
        run: pnpm prettier:check

  sort-package-json:
    runs-on: ubuntu-latest
    needs: [eslint, typescheck, prettier]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup
        with:
          node-version: "20"

      - name: Run Sort Package Json Check
        run: pnpm sort-package-json:check

  build:
    runs-on: ubuntu-latest
    needs: [eslint, typescheck, prettier, sort-package-json]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup
        with:
          node-version: "20"

      - name: Run Build
        run: pnpm build

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/common-actions/setup
        with:
          node-version: "20"

      - name: Run Tests
        run: pnpm test
