name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_PAT }}

      - uses: ./.github/common-actions/setup

      - run: pnpm build

      - id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset:release
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
