name: Semantic PR Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  validate-pr-title:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
      statuses: write

    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test

          requireScope: true

          headerPattern: '^(\w+)\(([a-z]+)\): (.+)$'
          headerPatternCorrespondence: type, scope, subject

          subjectPattern: '^[a-zA-Z0-9\s\-_.,!]{1,50}$'
          subjectPatternError: |
            The subject {subject} in pull request title {title}
            must be max 50 characters, and can only contain:
            letters (a–z, A–Z), numbers, spaces, dash, underscore, dot, comma, and exclamation mark.

          ignoreLabels: |
            Version Packages
            Revert
            bot

          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
