name: Semantic PR Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  validate-pr-title:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write

    steps:
      - name: Validate semantic pull request
        uses: amannn/action-semantic-pull-request@v5.5.3
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: true
          headerPattern: '^([a-z]+)\(([a-z]+)\): (.+)$'
          headerPatternCorrespondence: type,scope,subject
          subjectPattern: "^.{1,50}$"
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject:
            - is not empty
            - is maximum 50 characters long
            - matches commitlint rules: type(scope): subject
          wip: true
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

          ignoreLabels: |
            bot
            ignore-semantic-pull-request

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
