name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test

          requireScope: true

          headerPattern: '^(\w+)\(([a-z]+)\): (.+)$'
          headerPatternCorrespondence: type, scope, subject

          subjectPattern: '^[a-zA-Z0-9\s\-_.,!]{1,50}$'
          subjectPatternError: |
            The subject "{subject}" in pull request title "{title}"
            must be max 50 characters, and can only contain:
            letters (a–z, A–Z), numbers, spaces, dash, underscore, dot, comma, and exclamation mark.

          ignoreLabels: |
            Version Packages
            bot

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
