name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  upload-coverage:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/common-actions/setup

      - name: Build packages
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=packages
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.scanner.clean=true
