name: SonarQube

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - uses: ./.github/common-actions/setup

      - run: pnpm jest:coverage

      - run: cat coverage/lcov.info

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=packages
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.scanner.clean=true
